"""add_pipeline_files_table

Revision ID: 0645a87cd34f
Revises: 92e62c76cc1a
Create Date: 2026-03-19 15:56:30.368565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0645a87cd34f'
down_revision: Union[str, Sequence[str], None] = '92e62c76cc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('target_pixel_size', sa.Integer(), nullable=False),
    sa.Column('num_colors', sa.Integer(), nullable=False),
    sa.Column('dither_method', sa.String(length=32), nullable=False),
    sa.Column('dither_strength', sa.Float(), nullable=False),
    sa.Column('alpha_threshold', sa.Integer(), nullable=False),
    sa.Column('min_component_size', sa.Integer(), nullable=False),
    sa.Column('add_outline', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_files')
    # ### end Alembic commands ###
