"""add target_width and target_height to nobg_files

Revision ID: 92e62c76cc1a
Revises: adc1a1a576a5
Create Date: 2026-03-19 14:39:25.685439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '92e62c76cc1a'
down_revision: Union[str, Sequence[str], None] = 'adc1a1a576a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downscaled_files_source_file_id'), table_name='downscaled_files')
    op.drop_index(op.f('ix_downscaled_files_source_type'), table_name='downscaled_files')
    op.drop_table('downscaled_files')
    op.add_column('nobg_files', sa.Column('target_width', sa.Integer(), nullable=False))
    op.add_column('nobg_files', sa.Column('target_height', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nobg_files', 'target_height')
    op.drop_column('nobg_files', 'target_width')
    op.create_table('downscaled_files',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_file_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_type', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_width', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_height', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('downscaled_files_pkey')),
    sa.UniqueConstraint('s3_key', name=op.f('downscaled_files_s3_key_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_downscaled_files_source_type'), 'downscaled_files', ['source_type'], unique=False)
    op.create_index(op.f('ix_downscaled_files_source_file_id'), 'downscaled_files', ['source_file_id'], unique=False)
    # ### end Alembic commands ###
