"""Update migrations

Revision ID: 95b1a283c466
Revises: 
Create Date: 2026-03-14 00:22:50.336178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b1a283c466'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pixelized_files', 'num_colors',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pixelized_files', 'palette_name')
    op.drop_column('pixelized_files', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pixelized_files', sa.Column('mode', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('pixelized_files', sa.Column('palette_name', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('pixelized_files', 'num_colors',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
