"""Initial tables

Revision ID: a64cdc62c8d8
Revises: 
Create Date: 2026-03-14 00:31:19.747219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a64cdc62c8d8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('kernel_size', sa.Integer(), nullable=False),
    sa.Column('alpha_threshold', sa.Integer(), nullable=False),
    sa.Column('iterations', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_cleanup_files_source_file_id'), 'cleanup_files', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_cleanup_files_source_type'), 'cleanup_files', ['source_type'], unique=False)
    op.create_table('downscaled_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('target_width', sa.Integer(), nullable=False),
    sa.Column('target_height', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_downscaled_files_source_file_id'), 'downscaled_files', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_downscaled_files_source_type'), 'downscaled_files', ['source_type'], unique=False)
    op.create_table('original_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_table('pixelized_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('num_colors', sa.Integer(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_index(op.f('ix_pixelized_files_source_file_id'), 'pixelized_files', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_pixelized_files_source_type'), 'pixelized_files', ['source_type'], unique=False)
    op.create_table('nobg_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_file_id', sa.UUID(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['original_file_id'], ['original_files.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('nobg_files')
    op.drop_index(op.f('ix_pixelized_files_source_type'), table_name='pixelized_files')
    op.drop_index(op.f('ix_pixelized_files_source_file_id'), table_name='pixelized_files')
    op.drop_table('pixelized_files')
    op.drop_table('original_files')
    op.drop_index(op.f('ix_downscaled_files_source_type'), table_name='downscaled_files')
    op.drop_index(op.f('ix_downscaled_files_source_file_id'), table_name='downscaled_files')
    op.drop_table('downscaled_files')
    op.drop_index(op.f('ix_cleanup_files_source_type'), table_name='cleanup_files')
    op.drop_index(op.f('ix_cleanup_files_source_file_id'), table_name='cleanup_files')
    op.drop_table('cleanup_files')
    # ### end Alembic commands ###
