"""update cleanup image model

Revision ID: adc1a1a576a5
Revises: a64cdc62c8d8
Create Date: 2026-03-15 13:28:29.034922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adc1a1a576a5'
down_revision: Union[str, Sequence[str], None] = 'a64cdc62c8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleanup_files', sa.Column('min_component_size', sa.Integer(), nullable=False))
    op.add_column('cleanup_files', sa.Column('add_outline', sa.Boolean(), nullable=False))
    op.drop_column('cleanup_files', 'iterations')
    op.drop_column('cleanup_files', 'kernel_size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cleanup_files', sa.Column('kernel_size', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('cleanup_files', sa.Column('iterations', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cleanup_files', 'add_outline')
    op.drop_column('cleanup_files', 'min_component_size')
    # ### end Alembic commands ###
